### ISSUE TITLE
`ID2D1Bitmap1.Map()` only returns 1 row of pixel data

### ISSUE THREAD

**Issue by d2phap** [smourier/WicNet#4]
Hi @smourier,

As my post from https://github.com/smourier/DirectN/issues/34, I modified the function a bit to load all pixel data into a `DataGridView`.

```cs
public void LoadPixelDataIntoDataGrid()
{
    var bmpProps = new D2D1_BITMAP_PROPERTIES1()
    {
        bitmapOptions = D2D1_BITMAP_OPTIONS.D2D1_BITMAP_OPTIONS_CANNOT_DRAW | D2D1_BITMAP_OPTIONS.D2D1_BITMAP_OPTIONS_CPU_READ,
        pixelFormat = new D2D1_PIXEL_FORMAT()
        {
            alphaMode = D2D1_ALPHA_MODE.D2D1_ALPHA_MODE_PREMULTIPLIED,
            format = DXGI_FORMAT.DXGI_FORMAT_B8G8R8A8_UNORM,
        },
        dpiX = 96.0f,
        dpiY = 96.0f,
    };

    var size = _imageD2D.GetSize().ToD2D_SIZE_U();
    using var bitmap1 = _device.CreateBitmap<ID2D1Bitmap1>(size, bmpProps);
    bitmap1.CopyFromBitmap(_imageD2D);

    var map = bitmap1.Map(D2D1_MAP_OPTIONS.D2D1_MAP_OPTIONS_READ);
    var dataSize = (int)(size.width * size.height * 4);

    var bytes = new byte[dataSize];
    Marshal.Copy(map.bits, bytes, 0, dataSize);
    bitmap1.Unmap();

    // load all pixel data into data grid view
    dt.DataSource = bytes.Select((i, index) => new
    {
        Index = index,
        Value = i.ToString(),
    }).ToList();
}
```

## The problem 
It only returns the first row of the pixel data; the rest values are just 0!
In the demo, I used 4x4 PNG image with alpha pixels, and draw 100X onto the window.

![image](https://user-images.githubusercontent.com/3154213/221390897-5c083ef5-49a7-4f64-944a-a4a5c176f07d.png)

### Full source code:
[WinFormsApp1.zip](https://github.com/smourier/WicNet/files/10832887/WinFormsApp1.zip)

**Comment by d2phap** [comment]
I managed to fix it.

```diff
- var dataSize = (int)(size.width * size.height * 4);
+ var dataSize = (int)(size.height * map.pitch);
```

According to https://learn.microsoft.com/en-us/windows/win32/api/d2d1_1/ns-d2d1_1-d2d1_mapped_rect, _`pitch` is the size in bytes of an individual scanline in the bitmap_. So the `dataSize` should be calculated by image height times pitch.

**Comment by smourier** [comment]
Yes, this is also called the stride, it depends on the bitmap layout in memory, you never want to assume things like "4" https://learn.microsoft.com/en-us/windows/win32/medfound/image-stride
