### ISSUE TITLE
Wic supports heic and WebP, but does not support JP2000 ?

### ISSUE THREAD

**Issue by Charltsing** [smourier/WicNet#8]
Windows10 22h2 19045.4651

i try code
using (var bmp = WicNet.WicBitmapSource.Load(imgfullname))
{
    width = bmp.Width;
    height = bmp.Height;
}

if i open a jp2000 image , it report 80004005 (Component not found).
[jp2.zip](https://github.com/user-attachments/files/16402283/jp2.zip)

heic and webp image can get width and height

so how to read jp2000 with wic ? 
Or would you like to extend the function of WicNet to support JP2000?

**Comment by smourier** [comment]
To be able to read (or write) an image file in WIC, the corresponding WIC component needs to be installed on the PC.

Windows doesn't have anything to read .jp2 file on a standard Windows box, so it doesn't work in Windows (doesn't open in Explorer when double-clicked), doesn't work in WIC, and doesn't work in WicNet.

You can use [WicNet Explorer](https://github.com/smourier/WicNet/tree/main/WicNetExplorer) to check what files are supported (menu Tools / Show Decodable File Extensions):

![image](https://github.com/user-attachments/assets/ec39debd-1ae9-400f-9535-59668662dd3a)

You can write your and register own WIC component that supports jp2 or buy one that does it and it will work in WicNet automatically.

**Comment by Charltsing** [comment]
I couldn't find any JP2000 components that support Wic
